商品詳細１
ryushin0316/furima-33389 pull request #7
Opened 2021-05-15 07:26 UTC by ryushin0316

# What
商品詳細機能の実装

# Why
商品の詳細が確認できる

ログイン状態の出品者のみ、「編集・削除ボタン」が表示されること
https://gyazo.com/0b97600bb711d3c5b76854f73e1061a0

ログイン状態の出品者以外のユーザーのみ、「購入画面に進むボタン」が表示されること
https://gyazo.com/0f02ed32665888e78b084af7a9bab173

ログアウト状態のユーザーでも、商品詳細表示ページを閲覧できること
ログアウト状態のユーザーには、「編集・削除・購入画面に進むボタン」が表示されないこと
商品出品時に登録した情報が見られるようになっていること
https://gyazo.com/b71aa3fde1f26a9b5cfee0afa1b35511

2021-05-15 07:43 UTC, ken-1853 reviewed
レビュー依頼ありがとうございます！
修正点確認させていただきました。
コメントいたしましたので、ご確認お願いします！

修正頂いた後、コミットプッシュを確認いただき、再度レビュー依頼のご提出をお願い致します！

2021-05-15 07:43 UTC, ken-1853 commented on app/controllers/items_controller.rb
> +    @items = Item.all
```
   @items = Item.all
```
一覧表示機能で実装した内容を上書きするような記述になってしまっています。
5行目の記述で要件は満たされているので、6行目は削除しましょう

2021-05-15 07:43 UTC, ken-1853 commented on app/controllers/items_controller.rb
> +    end
```
 if user_signed_in?
     @item = Item.new      
    else
      redirect_to user_session_path(@item.id)
    end
```
こちら出品機能で実装されている内容から変更されてしまっているようです。
LGTMが出た内容から変更してしまうと、レビューの効果が薄れてしまうので、特段の理由がなければLGTMをもらった時の記述で統一しておきましょう！

ちなみにですが、ユーザーがログインしていない時の制限は、authenticate_user!で実現できているため、別途の記述は不要です

2021-05-15 07:43 UTC, ken-1853 commented on app/views/items/show.html.erb
>      <%# ログインしているユーザーと出品しているユーザーが、同一人物の場合と同一人物ではない場合で、処理を分けましょう %>
```
 <%# ログインしているユーザーと出品しているユーザーが、同一人物の場合と同一人物ではない場合で、処理を分けましょう %>
```
こちらのコメントアウトですが、不要であれば削除しましょう。
もし必要であれば、第三者でもわかるように「残す目的」「なぜ必要か」という理由などを、コメントとして書いておくことをおすすめいたします。

ここ以外もご自身で確認いただいて、不要なコメントアウトが残っていましたら、同様に削除しましょう！（未実装の箇所は残っていて構いません）

2021-05-15 07:43 UTC, ken-1853 commented on app/views/items/show.html.erb
>    <a href="#" class="another-item"><%= "商品のカテゴリー名" %>をもっと見る</a>
```
<a href="#" class="another-item"><%= "商品のカテゴリー名" %>をもっと見る</a>
```
こちらの記述を、商品のカテゴリーが表示されるように変更しましょう

2021-05-17 02:54 UTC, shodai-ito requested changes
レビュー依頼ありがとうございます！
コメントしましたので、ご確認をお願いいたします！

その後、再度レビュー依頼フォームのご提出をよろしくお願いいたします。

2021-05-17 02:54 UTC, shodai-ito commented on app/controllers/items_controller.rb
> +    end
```
if user_signed_in?
     @item = Item.new      
    else
      redirect_to user_session_path(@item.id)
    end

```
こちら出品機能で実装されている内容から変更されてしまっているようです。
LGTMが出た内容から変更してしまうと、レビューの効果が薄れてしまうので、特段の理由がなければLGTMをもらった時の記述で統一しておきましょう！

ちなみにですが、ユーザーがログインしていない時の制限は、authenticate_user!で実現できているため、別途の記述は不要です！

2021-05-17 02:54 UTC, shodai-ito commented on app/controllers/items_controller.rb
> +      redirect_to items_path
こちらも修正いただく必要はございません！
元の記述に戻しておきましょう！

2021-05-17 02:54 UTC, shodai-ito commented on app/views/items/show.html.erb
> +<%= link_to item_path(@item.id), method: :get do %>
`<%= link_to item_path(@item.id), method: :get do %>`
既に商品の詳細ページに遷移しているので、こちらのリンクは不要です！

2021-05-17 02:54 UTC, shodai-ito commented on app/views/items/show.html.erb
>        <span><%= "商品説明" %></span>
こちら商品の説明カラムが表示されるようにしましょう！

2021-05-17 03:18 UTC, saki125 reviewed
レビュー依頼ありがとうございます。
修正点確認させていただきました。
追加で1点コメントいたしました。非常に細かい部分で恐縮ではございますが、ご確認いただけますと幸いです。
修正後再度、レビュー依頼フォームのご提出をお願いいたします。
お手数をお掛け致しますが、よろしくお願いいたします。

2021-05-17 03:18 UTC, saki125 commented on app/views/items/show.html.erb
> +      <span><%= @item.text.name %></span>
```ruby
<span><%= @item.text.name %></span>
```
商品説明のカラムはtextを使用しておりますので以下のように記述することが可能かと存じます。
```ruby
<span><%= @item.text %></span>
```
こちら修正後、商品説明が表示されることを確認してください。

2021-05-17 03:22 UTC, shodai-ito reviewed
レビュー依頼ありがとうございます！
修正点確認させていただきました！
コメントしましたので、ご確認をお願いいたします！

その後、再度レビュー依頼フォームのご提出をよろしくお願いいたします。

2021-05-17 03:22 UTC, shodai-ito commented on app/controllers/items_controller.rb
> -    @item = Item.new
newアクションに
`@item = Item.new`
の記述は必要です！

2021-05-17 03:25 UTC, saki125 commented
レビュー依頼ありがとうございます！
LGTMとさせていただきます。実装お疲れさまでした。

こちらのブランチは忘れずにMergeいただき、ローカルのMasterにPullした後に次の実装のためのブランチを切るようにしましょう。
引き続き実装頑張ってください！応援しております。

2021-05-17 04:02 UTC, merged